lib/tarjetas_web/router.ex
defmodule TarjetasWeb.Router do
  use TarjetasWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TarjetasWeb do
    pipe_through :browser # Use the default browser stack

    resources "/users", UserController, only: [:new, :create]
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    get "/", HomeController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", TarjetasWeb do
  #   pipe_through :api
  # end
end

lib/tarjetas/accounts/accounts.ex
defmodule Tarjetas.Accounts do
  import Ecto.Query, warn: false
  alias Tarjetas.Repo

  alias Tarjetas.Accounts.User

  def get_user!(id), do: Repo.get!(User, id)

  def find_user_by_username(username)
  when is_binary(username) do
    from(u in User, where: u.username == ^username)
    |> Repo.one()
    |> case do
      %User{} = user ->
        {:ok, user}
      _ ->
        {:error, :not_found}
    end
  end

  def find_user_by_username(_username) do
    {:error, :not_found}
  end

  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end

  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  def authenticate(%User{} = user, password) do
    Comeonin.Argon2.check_pass(user, password)
    |> case do
      {:ok, user} ->
        {:ok, user}
      _ ->
        {:error, :not_authorized}
    end
  end

  def authenticate(username, password)
  when is_binary(username) and is_binary(password)
  do
    case find_user_by_username(username) do
      {:ok, user} ->
        authenticate(user, password)
      _ ->
        {:error, :not_authorized}
    end
  end

  def authenticate(_username, _password) do
    {:error, :not_authorized}
  end
end

lib/tarjetas/accounts/user.ex
defmodule Tarjetas.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  @minimum_username_length 2
  @maximum_username_length 50
  @minimum_password_length 8

  schema "users" do
    field :username, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    field :password_hash, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs \\ %{}) do
    user
    |> cast(attrs, [:username, :password, :password_confirmation])
    |> validate_required([:username, :password, :password_confirmation])
    |> validate_length(:username, min: @minimum_username_length, max: @maximum_username_length)
    |> validate_length(:password, min: @minimum_password_length)
    |> unique_constraint(:username)
    |> validate_passwords_match()
    |> hash_password()
    |> clear_plaintext_passwords()
  end

  defp validate_passwords_match(%{changes: %{password: password, password_confirmation: password_confirmation}} = changeset)
  when password == password_confirmation, do: changeset

  defp validate_passwords_match(changeset) do
    add_error(changeset, :password, "doesn't match confirmation")
  end

  defp hash_password(%{valid?: true, changes: %{password: password}} = changeset) do
    put_change(changeset, :password_hash, Comeonin.Argon2.hashpwsalt(password))
  end

  defp hash_password(changeset), do: changeset

  defp clear_plaintext_passwords(changeset) do
    change(changeset, %{password: nil, password_confirmation: nil})
  end
end

lib/tarjetas/application.ex
defmodule Tarjetas.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Tarjetas.Repo, []),
      # Start the endpoint when the application starts
      supervisor(TarjetasWeb.Endpoint, []),
      # Start your own worker by calling: Tarjetas.Worker.start_link(arg1, arg2, arg3)
      # worker(Tarjetas.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Tarjetas.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TarjetasWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/tarjetas/repo.ex
defmodule Tarjetas.Repo do
  use Ecto.Repo, otp_app: :tarjetas

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/tarjetas_web/controllers/home_controller.ex
defmodule TarjetasWeb.HomeController do
  use TarjetasWeb, :controller

  import TarjetasWeb.Plugs.Authentication

  plug :authenticate_user

  def show(conn, _params) do
    render(conn, "show.html")
  end
end

lib/tarjetas_web/controllers/session_controller.ex
defmodule TarjetasWeb.SessionController do
  use TarjetasWeb, :controller

  alias Tarjetas.Accounts

  def new(conn, _params) do
    render(conn, "new.html", conn: conn)
  end

  def create(conn, %{"username" => username, "password" => password}) do
    Accounts.authenticate(username, password)
    |> case do
      {:ok, user} ->
        create_session(conn, user)
      _ ->
        reject_session(conn)
    end
  end

  def delete(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: home_path(conn, :show))
  end

  defp create_session(conn, user) do
    conn
    |> put_flash(:info, "Welcome back!")
    |> put_session(:user_id, user.id)
    |> configure_session(renew: true)
    |> redirect(to: home_path(conn, :show))
  end

  defp reject_session(conn) do
    conn
    |> put_flash(:error, "That didn't work.")
    |> render("new.html", conn: conn)
  end
end

lib/tarjetas_web/controllers/user_controller.ex
defmodule TarjetasWeb.UserController do
  use TarjetasWeb, :controller

  alias Tarjetas.Accounts
  alias Tarjetas.Accounts.User

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

	def create(conn, %{"user" => user_params}) do
		case Accounts.create_user(user_params) do
			{:ok, _user} ->
				conn
				|> put_flash(:info, "User created successfully.")
				|> redirect(to: home_path(conn, :show))
			{:error, %Ecto.Changeset{} = changeset} ->
				render(conn, "new.html", changeset: changeset)
		end
	end
end

lib/tarjetas_web/views/error_view.ex
defmodule TarjetasWeb.ErrorView do
  use TarjetasWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/tarjetas_web/views/home_view.ex
defmodule TarjetasWeb.HomeView do
  use TarjetasWeb, :view
end

lib/tarjetas_web/views/layout_view.ex
defmodule TarjetasWeb.LayoutView do
  use TarjetasWeb, :view
end

lib/tarjetas_web/views/session_view.ex
defmodule TarjetasWeb.SessionView do
  use TarjetasWeb, :view
end

lib/tarjetas_web/views/user_view.ex
defmodule TarjetasWeb.UserView do
  use TarjetasWeb, :view
end

lib/tarjetas_web/templates/home/show.html.eex
<p>You are signed in as <strong><%= @current_user.username %></strong>.</p>

<%= form_for @conn, session_path(@conn, :delete), [method: :delete], fn _f -> %>
  <%= submit "Sign out", class: "btn btn-primary" %>
<% end %>

lib/tarjetas_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Tarjetas!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="jumbotron">
      <h1 class="display-4">Tarjetas</h1>
      <p class="lead">Para el aprender español por tarjetas de memoria.</p>

      <hr class="my-4"/>

      <p>Sign up for free, no email address required..</p>
    </div>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/tarjetas_web/templates/session/new.html.eex
<%= form_for @conn, session_path(@conn, :create), fn f -> %>
  <%= input(f, :username, "Enter your username") %>
  <%= input(f, :password, "Enter your password") %>

  <div class="form-group">
    <%= submit "Sign in", class: "btn btn-primary"  %>
    or <%= link "create an account", to: user_path(@conn, :new) %>
  </div>
<% end %>

lib/tarjetas_web/templates/user/new.html.eex
<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= input(f, :username, "Choose a username") %>
  <%= input(f, :password, "Choose a password") %>
  <%= input(f, :password_confirmation, "Type the password again") %>

  <%= submit "Submit", class: "btn btn-primary"  %>

  <div class="mt-3">
    Already have an account?
    <%= link("Sign in", to: session_path(@conn, :new)) %>
  </div>
<% end %>